name: Secrets and Variables

on:
  push:
    branches: [main]
  workflow_dispatch:

env:                                 # Workflow-level env vars
  APP_ENV: production

jobs:
  deploy:
    environment:
      name: dev
    runs-on: ubuntu-latest
    env:                             # Job-level env vars
      REGION: eastus
    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        run: |
          # curl -H "Authorization: token ${{ secrets.DEPLOY_TOKEN }}" \
          #      https://api.example.com/deploy
          echo  ${{ secrets.DEPLOY_TOKEN }}

      - run: echo "Deploying to $REGION"
      - run: echo "App name is ${{ vars.APP_NAME }}"  # Repository/org variable
