name: Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    environment:
      name: production
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      - run: echo "Validating at $(date)"

